// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwPirVLs1NWOCJlAkASbvGF03G4OaC4xc',
    appId: '1:395559427991:web:bfffe48016a36187996ed2',
    messagingSenderId: '395559427991',
    projectId: 'mobile-dashboard-3a62c',
    authDomain: 'mobile-dashboard-3a62c.firebaseapp.com',
    storageBucket: 'mobile-dashboard-3a62c.firebasestorage.app',
    measurementId: 'G-HC94PH0K2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA__fiIiJMf9OeXRK89j7c4RE5nON5Mw40',
    appId: '1:395559427991:android:da2301bb12437bc3996ed2',
    messagingSenderId: '395559427991',
    projectId: 'mobile-dashboard-3a62c',
    storageBucket: 'mobile-dashboard-3a62c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6J7MhLGHH-xn3jE_KQM1mJrIIWYUBP34',
    appId: '1:395559427991:ios:fdd8dcc770a6b0b3996ed2',
    messagingSenderId: '395559427991',
    projectId: 'mobile-dashboard-3a62c',
    storageBucket: 'mobile-dashboard-3a62c.firebasestorage.app',
    iosBundleId: 'com.example.inditexOccupancy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6J7MhLGHH-xn3jE_KQM1mJrIIWYUBP34',
    appId: '1:395559427991:ios:fdd8dcc770a6b0b3996ed2',
    messagingSenderId: '395559427991',
    projectId: 'mobile-dashboard-3a62c',
    storageBucket: 'mobile-dashboard-3a62c.firebasestorage.app',
    iosBundleId: 'com.example.inditexOccupancy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwPirVLs1NWOCJlAkASbvGF03G4OaC4xc',
    appId: '1:395559427991:web:eb9a78337cef7d37996ed2',
    messagingSenderId: '395559427991',
    projectId: 'mobile-dashboard-3a62c',
    authDomain: 'mobile-dashboard-3a62c.firebaseapp.com',
    storageBucket: 'mobile-dashboard-3a62c.firebasestorage.app',
    measurementId: 'G-9H9BX1HKM7',
  );
}
